export const LIST_TABLE_NAME = [
    'EGML_EMAIL_DATA',
    'EGML_EMAIL_ADDRESS',
    'EGML_EMAIL_ATTACHMENT_LINK',
    'EGML_EMAIL_ATTACHMENT',
    'EGML_EMAIL_DATA_ALT',
    'EGML_EMAIL',
    'EGPL_CASEMGMT_CASE_ASS',
    'EGPL_EVENT_HISTORY_CASE_MGMT',
    'EGPL_CASEMGMT_ACTIVITY',
    'EGPL_CASEMGMT_CASE',
    'EGPL_CASEMGMT_CONTACT_POINT',
    'EGPL_CASEMGMT_CPOINT_EMAIL',
    'EGPL_CASEMGMT_CUSTOMER',
    'EGPL_DEPARTMENT',
    'EGPL_NOTES',
    'EGPL_ROUTING_QUEUE',
    'EGPL_USER',
];

export const OPERATION = {
    DELETE: 1,
    INSERT: 2,
    UPDATE_BEFORE: 3,
    UPDATE_AFTER: 4,
};